service: dummyjs
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  dummy:
    handler: handler.dummy
    timeout: 300
    events:
      - httpApi:
          path: /
          method: post
	
plugins:
  - serverless-offline
